avalon/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gm.urls')),
]

gm/urls.py
from django.conf.urls import url
#from django.core.urlresolvers import reverse

from gm import views

app_name = 'gm'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create$', views.GameCreateView.as_view(), name='create'),
    url(r'^player_create$', views.PlayerCreateView.as_view(), name='player_create'),
    url(r'^(?P<pk>[-\w]+)/details$', views.GameDetailView.as_view(), name='details'),
    url(r'^stats_update$', views.updateGameStats, name='stats_update'),
]

gm/models.py
# -*- coding: utf-8 -*-
from __future__ import division
from django.db import models
from django.db.models import Count, Sum
from django.core.validators import validate_comma_separated_integer_list
from numpy import diff
import trueskill

class Player(models.Model):
    tri = models.CharField(max_length=3)

    def save(self, *args, **kwargs):
        super(Player, self).save(*args, **kwargs)
        PlayerStats.objects.get_or_create(player=self)

class Game(models.Model):
    players = models.ManyToManyField(
        Player,
        through='Membership',
        through_fields=('game', 'player'    )
    )
    good_oberon = models.BooleanField()
    mission_cards = models.BooleanField()
    date = models.DateField()
    merlin_killed = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        super(Game, self).save(*args, **kwargs)
        self.update_or_create_stats()

    def update_or_create_stats(self):
        GameStats.objects.get_or_create(game=self)

    def get_role(self, role):
        try:
             return self.membership_set.filter(role=role).first().player
        except:
             return None

'''
    def get_roles(self, role):
        return ' '.join([v['player__tri'] for v in self.membership_set.filter(role=role).values('player__tri')])
'''

class Mission(models.Model):
    FAIL = 'F'
    SUCCESS = 'S'

    MISSION_RESULTS = (
        (FAIL, 'Fail'),
        (SUCCESS, 'Success'),
    )

    game = models.ForeignKey(Game, related_name='missions')
    result = models.CharField(max_length=2, choices=MISSION_RESULTS)
    leader = models.ForeignKey(Player)
    number = models.IntegerField()


class Membership(models.Model):
    PEON = 'PEO'
    GALAHAD = 'GAL'
    PERCEVAL = 'PER'
    MERLIN = 'MER'
    MORGANA = 'MOR'
    ASSASSIN = 'ASS'
    OBERON = 'OBE'
    MORDRED = 'MOD'

    ROLE_CHOICES = (
        (PEON, 'Peon'),
        (GALAHAD, 'Galahad'),
        (PERCEVAL, 'Perceval'),
        (MERLIN, 'Merlin'),
        (MORGANA, 'Morgana'),
        (ASSASSIN, 'Assassin'),
        (OBERON, 'Oberon'),
        (MORDRED, 'Mordred'),
    )

    player = models.ForeignKey(Player)
    game = models.ForeignKey(Game)
    position = models.IntegerField()
    role = models.CharField(
        max_length=3,
        choices=ROLE_CHOICES,
        default=PEON,
    )

    @property
    def bad(self):
        return self.role in [Membership.MORGANA, Membership.ASSASSIN, Membership.OBERON, Membership.MORDRED]

    @property
    def good(self):
        return not self.bad

    @property
    def faction(self):
        return 'good' if self.good() else 'evil'


class GameStats(models.Model):
    game = models.OneToOneField(Game, related_name='stats')

    good_win = models.BooleanField()
    n_players = models.IntegerField()

    merlin = models.ForeignKey(Player, blank=True, null=True, related_name='merlin')
    perceval = models.ForeignKey(Player, blank=True, null=True, related_name='perceval')
    galahad = models.ForeignKey(Player, blank=True, null=True, related_name='galahad')
    mordred = models.ForeignKey(Player, blank=True, null=True, related_name='mordred')
    morgana = models.ForeignKey(Player, blank=True, null=True, related_name='morgana')
    oberon = models.ForeignKey(Player, blank=True, null=True, related_name='oberon')
    assassin = models.ForeignKey(Player, blank=True, null=True, related_name='assassin')

    evil_team_tri = models.CharField(max_length=255)
    good_team_tri = models.CharField(max_length=255)

    mechants_pos = models.CharField(validators=[validate_comma_separated_integer_list], max_length=255)
    mechmech = models.BooleanField(help_text='deux méchant sont à côté')

    def save(self, *args, **kwargs):
        self.good_win = self.game.missions.filter(result='S').count() >= 3 and not self.game.merlin_killed
        self.n_players = self.game.players.all().count()

        self.merlin = self.game.get_role(role=Membership.MERLIN)
        self.perceval = self.game.get_role(role=Membership.PERCEVAL)
        self.galahad = self.game.get_role(role=Membership.GALAHAD)
        self.mordred = self.game.get_role(role=Membership.MORDRED)
        self.morgana = self.game.get_role(role=Membership.MORGANA)
        self.oberon = self.game.get_role(role=Membership.OBERON)
        self.assassin = self.game.get_role(role=Membership.ASSASSIN)

        pos = []
        tris = []
        for p in [self.mordred, self.morgana, self.oberon, self.assassin]:
            if p is not None:
                tris.append(p.tri)
                pos.append(p.membership_set.filter(game=self.game).first().position)
        self.mechants_pos = sorted(pos)
        self.evil_team_tri = ','.join(sorted(tris))
        self.mechmech = len(self.mechants_pos) and (any(diff(self.mechants_pos) == 1) or (self.mechants_pos[-1] - self.mechants_pos[0] == self.n_players - 1))

        tris = []
        for p in self.game.players.values_list('tri'):
            p = p[0]
            if p not in self.evil_team_tri:
                tris.append(p)
        self.good_team_tri = ','.join(sorted(tris))

        super(GameStats, self).save(*args, **kwargs)


class PlayerStats(models.Model):
    player = models.OneToOneField(Player, related_name='stats')

    n_game = models.IntegerField(default=0)
    n_game_evil = models.IntegerField(default=0)
    n_game_good = models.IntegerField(default=0)

    n_win = models.IntegerField(default=0)
    n_win_evil = models.IntegerField(default=0)
    n_win_good = models.IntegerField(default=0)

    pc_win = models.FloatField(default=0)
    pc_win_evil = models.FloatField(default=0)
    pc_win_good = models.FloatField(default=0)

    n_played_merlin = models.IntegerField(default=0)
    n_played_perceval = models.IntegerField(default=0)
    n_played_galahad = models.IntegerField(default=0)
    n_played_mordred = models.IntegerField(default=0)
    n_played_morgana = models.IntegerField(default=0)
    n_played_oberon = models.IntegerField(default=0)
    n_played_assassin = models.IntegerField(default=0)

    n_played_merlin_ratio = models.FloatField(default=0)
    n_played_perceval_ratio = models.FloatField(default=0)
    n_played_galahad_ratio = models.FloatField(default=0)
    n_played_mordred_ratio = models.FloatField(default=0)
    n_played_morgana_ratio = models.FloatField(default=0)
    n_played_oberon_ratio = models.FloatField(default=0)
    n_played_assassin_ratio = models.FloatField(default=0)

    ranking_trueskill = models.FloatField(default=0)

    n_arthur = models.IntegerField(default=0)
    n_mission_played = models.IntegerField(default=0)
    n_arthur_ratio = models.FloatField(default=0)

    def save(self, *args, **kwargs):
        if self.player.tri in ['EVI', 'GOO']:
            return super(PlayerStats, self).save(*args, **kwargs)

        gs_filt = Game.objects.filter(players=self.player)
        gs_filt_evil = gs_filt.filter(stats__evil_team_tri__contains=self.player.tri)
        gs_filt_good = gs_filt.exclude(stats__evil_team_tri__contains=self.player.tri)

        self.n_game = gs_filt.count()
        self.n_game_evil = gs_filt_evil.count()
        self.n_game_good = gs_filt_good.count()

        self.n_win_evil = gs_filt_evil.filter(stats__good_win=False).count()
        self.n_win_good = gs_filt_good.filter(stats__good_win=True).count()
        self.n_win = self.n_win_evil + self.n_win_good

        if self.n_game:
            self.pc_win = self.n_win * 100 / self.n_game
        if self.n_game_good:
            self.pc_win_good = self.n_win_good * 100 / self.n_game_good
        if self.n_game_evil:
            self.pc_win_evil = self.n_win_evil * 100 / self.n_game_evil

        self.n_played_merlin = Membership.objects.filter(player=self.player).filter(role=Membership.MERLIN).count()
        self.n_played_perceval = Membership.objects.filter(player=self.player).filter(role=Membership.PERCEVAL).count()
        self.n_played_galahad = Membership.objects.filter(player=self.player).filter(role=Membership.GALAHAD).count()
        self.n_played_mordred = Membership.objects.filter(player=self.player).filter(role=Membership.MORDRED).count()
        self.n_played_morgana = Membership.objects.filter(player=self.player).filter(role=Membership.MORGANA).count()
        self.n_played_oberon = Membership.objects.filter(player=self.player).filter(role=Membership.OBERON).count()
        self.n_played_assassin = Membership.objects.filter(player=self.player).filter(role=Membership.ASSASSIN).count()

        if self.n_game:
            self.n_played_merlin_ratio = self.n_played_merlin / self.n_game * 100
            self.n_played_perceval_ratio = self.n_played_perceval / self.n_game * 100
            self.n_played_galahad_ratio = self.n_played_galahad / self.n_game * 100
            self.n_played_mordred_ratio = self.n_played_mordred / self.n_game * 100
            self.n_played_morgana_ratio = self.n_played_morgana / self.n_game * 100
            self.n_played_oberon_ratio = self.n_played_oberon / self.n_game * 100
            self.n_played_assassin_ratio = self.n_played_assassin / self.n_game * 100

        self.n_arthur = Mission.objects.all().filter(leader=self.player).count()
        self.n_mission_played = Game.objects.all().filter(players=self.player).annotate(count=Count('missions')).aggregate(r=Sum('count'))['r'] or 0
        if self.n_mission_played > 0:
            self.n_arthur_ratio = self.n_arthur / self.n_mission_played * 100

        super(PlayerStats, self).save(*args, **kwargs)

def update_rankings():
    ps = PlayerStats.objects

    ratings = {tri[0]: trueskill.Rating() for tri in Player.objects.values_list('tri')}
    ratings['EVI'] = trueskill.Rating(55)
    ratings['GOO'] = trueskill.Rating(-5)
    for game in GameStats.objects.all().order_by('game__date'):
        evil_tri = game.evil_team_tri + ',EVI'
        good_tri = game.good_team_tri + ',GOO'
        evil_team = [ratings[tri] for tri in evil_tri.split(',')]

gm/views.py
# -*- coding: utf-8 -*-
from __future__ import division
from django.core.urlresolvers import reverse_lazy
from django.db.models import Count, F, Max, Min, Q
from django.shortcuts import redirect
from django.views import generic
from gm.models import Game, GameStats, Membership, Mission, Player, PlayerStats, update_rankings
from gm import ped

# todo: move that the GameStats manager
MIN_GAME_STATS = 4


def r(n):
    return round(n, 2)

def j(queryset):
    ''' join a queryset. '''
    return ', '.join([s[0] for s in queryset])

def displayedStats():

    gs = GameStats.objects

    stats = {}
    stats['n_game'] = gs.all().count()
    stats['n_evilwon'] = gs.filter(good_win=False).count()
    stats['n_goodwon'] = gs.filter(good_win=True).count()
    stats['n_evilwon_ratio'] = r(stats['n_evilwon'] / stats['n_game'] * 100)
    stats['n_goodwon_ratio'] = r(stats['n_goodwon'] / stats['n_game'] * 100)

    # Sylvain et Marc dans la même équipe
    gs_filt = Game.objects.filter(players__tri__contains='SSA').filter(players__tri__contains='MPR')
    stats['n_ssa_and_mpr_game'] = gs_filt.count()
    stats['n_ssa_and_mpr'] = 0
    for q in gs_filt:
        a = q.membership_set.get(player__tri='SSA').good
        b = q.membership_set.get(player__tri='MPR').good
        if a == b:
            stats['n_ssa_and_mpr'] += 1
    stats['n_ssa_and_mpr_ratio'] =  r(stats['n_ssa_and_mpr'] / stats['n_ssa_and_mpr_game'] * 100)

    # Stats quand PED est là / pas là
    gs_filt = Game.objects.filter(players__tri__contains='PED')
    stats['withPED_n_evilwon'] = gs_filt.filter(stats__good_win=False).count()
    stats['withPED_n_game'] = gs_filt.count()
    stats['withPED_n_evilwon_ratio'] = r(stats['withPED_n_evilwon'] / stats['withPED_n_game'] * 100)

    gs_filt = Game.objects.exclude(players__tri__contains='PED')
    stats['withoutPED_n_evilwon'] = gs_filt.filter(stats__good_win=False).count()
    stats['withoutPED_n_game'] = gs_filt.count()
    stats['withoutPED_n_evilwon_ratio'] = r(stats['withoutPED_n_evilwon'] / stats['withoutPED_n_game'] * 100)

    # à côté d'un méchant, y'a un méchant
    stats['n_mechmech'] = gs.filter(mechmech=True).count()
    stats['n_mechmech_ratio'] = r(stats['n_mechmech'] / stats['n_game'] * 100)

    # tbe is oberon
    stats['tbe_oberon'] = gs.filter(oberon__tri='TBE').count()
    stats['tbe_n_game'] = PlayerStats.objects.filter(player__tri='TBE')[0].n_game
    stats['tbe_oberon_ratio'] = r(stats['tbe_oberon'] / stats['tbe_n_game'] * 100)

    # best player
    stats['best_player_ratio'] = PlayerStats.objects.filter(n_game__gt=MIN_GAME_STATS).exclude(player__tri='AJA').aggregate(Max('pc_win'))['pc_win__max']
    stats['best_player'] = j(PlayerStats.objects.filter(n_game__gt=MIN_GAME_STATS).exclude(player__tri='AJA').filter(pc_win=stats['best_player_ratio']).values_list('player__tri'))
    stats['best_player_ratio'] = r(stats['best_player_ratio'])

    # roles
    for role in ['merlin', 'perceval', 'mordred', 'morgana', 'oberon', 'assassin']:
        stats['most_frequent_{}_ratio'.format(role)] = PlayerStats.objects.filter(n_game__gt=9).aggregate(Max('n_played_{}_ratio'.format(role)))['n_played_{}_ratio__max'.format(role)]
        kwargs = {'n_played_{}_ratio'.format(role): stats['most_frequent_{}_ratio'.format(role)], 'n_game__gt':9}
        stats['most_frequent_{}'.format(role)] = j(PlayerStats.objects.filter(**kwargs).values_list('player__tri'))
        stats['most_frequent_{}_ratio'.format(role)] = r(stats['most_frequent_{}_ratio'.format(role)])

    # never/always arthur
    na = PlayerStats.objects.all().filter(n_game__gt=MIN_GAME_STATS).exclude(player__tri='AJA')
    na = na.filter(n_arthur_ratio=na.aggregate(Min('n_arthur_ratio'))['n_arthur_ratio__min']).values_list('player__tri', 'n_arthur_ratio', 'n_mission_played')
    stats['never_arthur'] = j(na)
    stats['never_arthur_n_missions'] = na[0][2]
    stats['never_arthur_ratio'] = r(na[0][1])

    aa = PlayerStats.objects.all().filter(n_game__gt=MIN_GAME_STATS).exclude(player__tri='AJA')
    aa = aa.filter(n_arthur_ratio=aa.aggregate(Max('n_arthur_ratio'))['n_arthur_ratio__max']).values_list('player__tri', 'n_arthur_ratio', 'n_mission_played')
    stats['always_arthur'] = j(aa)
    stats['always_arthur_n_missions'] = aa[0][2]
    stats['always_arthur_ratio'] = r(aa[0][1])

    return stats

def missionStats():
    stats = {}
    l = Mission.objects.all()
    stats['count'] = l.count()
    stats['count_fail'] = l.filter(result=Mission.FAIL).count()
    stats['count_success'] = l.filter(result=Mission.SUCCESS).count()
    ea = l.filter(result=Mission.FAIL).values_list('leader__tri').annotate(count=Count('leader__tri'))
    stats['evil_arthur'] = list(ea.filter(count=ea.aggregate(Max('count'))['count__max']))
    ga = l.filter(result=Mission.SUCCESS).values_list('leader__tri').annotate(count=Count('leader__tri'))
    stats['good_arthur'] = list(ga.filter(count=ga.aggregate(Max('count'))['count__max']))

    em = l.filter(result=Mission.FAIL).filter(leader__tri=F('game__stats__merlin__tri')).values_list('leader__tri').annotate(count=Count('leader__tri'))
    stats['evil_merlin'] = list(em.filter(count=em.aggregate(Max('count'))['count__max']))
    gm = l.filter(result=Mission.SUCCESS).filter(leader__tri=F('game__stats__merlin__tri')).values_list('leader__tri').annotate(count=Count('leader__tri'))
    stats['good_merlin'] = list(gm.filter(count=gm.aggregate(Max('count'))['count__max']))

    return stats


class IndexView(generic.TemplateView):
    template_name = 'gm/home.html'
    context_object_name = 'gm_list'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['game_list'] = Game.objects.order_by('-date')
        context['player_list'] = Player.objects.filter(stats__n_game__gt=MIN_GAME_STATS).exclude(tri='AJA').order_by('-stats__pc_win')
        context['stats'] = displayedStats()
        context['mission_stats'] = missionStats()
        context['player_rank'] = Player.objects.filter((Q(stats__n_game__gt=MIN_GAME_STATS) & (~Q(tri='AJA')))| Q(tri='EVI') | Q(tri='GOO')).order_by('-stats__ranking_trueskill')
        context['min_game'] = MIN_GAME_STATS

        ped.update_context(context)
        return context


class GameCreateView(generic.edit.CreateView):
    model = Game
    fields = ['players', 'good_oberon', 'mission_cards', 'date']


class GameDetailView(generic.DetailView):
    model = Game


class PlayerCreateView(generic.edit.CreateView):
    model = Player
    fields = ['tri', ]
    success_url = reverse_lazy('gm:index')


def updateGameStats(request):
    for gamestats in GameStats.objects.all():
        gamestats.save()
    for playerstats in PlayerStats.objects.all():
        playerstats.save()
    update_rankings()
    return redirect('gm:index')

gm/templates/pages/games.html
<h4 class="title">All games details</h4>
{% if game_list %}
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
      <table class="table">
        <tr>
          <td>#</td>
          <td>Date</td>
          <td># Players</td>
          <td>Mission results</td>
          <td>Good won ?</td>
          <td>Merlin</td>
          <td>Perceval</td>
          <!-- <td>Galahad</td> -->
          <!-- <td>Peons</td> -->
          <td>Mordred</td>
          <td>Morgana</td>
          <td>Oberon</td>
          <td>Assassin</td>
          <!-- <td>Positions des méchants</td> -->
        </tr>
        {% for game in game_list %}
        <tr>
          <td style="font-weight: bold">{{ forloop.revcounter }}</td>
          <td><a href="{% url 'gm:details' game.pk %}">{{ game.date }}</a></td>
          <td>{{ game.stats.n_players }} </td>
          <td>
            {% for m in game.missions.all %}
              {% if m.result == 'S' %}
                <i class="glyphicon glyphicon-ok glyphicon-mission-ok"></i>
              {% else %}
                <i class="glyphicon glyphicon-remove glyphicon-mission-nok"></i>
              {% endif %}
            {% endfor %}
          </td>
          <td>
            {% if game.stats.good_win %}
              <i class="glyphicon glyphicon-ok glyphicon-mission-ok"></i>
            {% else %}
              <i class="glyphicon glyphicon-remove glyphicon-mission-nok"></i>
            {% endif %}
          </td>
          <td>{{ game.stats.merlin.tri }} </td>
          <td>{{ game.stats.perceval.tri }} </td>
          <!-- <td>{{ game.stats.galahad.tri }} </td> -->
          <!-- <td> </td> -->
          <td>{{ game.stats.mordred.tri }} </td>
          <td>{{ game.stats.morgana.tri }} </td>
          <td>{{ game.stats.oberon.tri }} </td>
          <td>{{ game.stats.assassin.tri }} </td>
          <!-- <td>{{ game.stats.mechants_pos }} </td> -->
        </tr>
        {% endfor %}
      </table>
    </div>
    <div class="col-xs-1"></div>
  </div>
{% else %}
  <p>No Games yet.</p>
{% endif %}

gm/templates/pages/general.html
<h4 class="title">Highlights</h4>
<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-10">

    <div class="row row-equal no-margin">

      <div class="col-sm-12">
        <div class="key_value">
          <div class="key">WANTED</div>
          <div class="value">
            {{ stats.best_player }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.best_player_ratio }}% of games won</span>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

<h4 class="title">General statistics on {{ stats.n_game }} games</h4>
<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-10">

    <div class="row row-equal no-margin">

      <div class="col-sm-4">
        <div class="key_value">
          <div class="key">Good Won</div>
          <div class="value">
            {{ stats.n_goodwon }}/{{ stats.n_game }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.n_goodwon_ratio }}%</span>
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="key_value">
          <div class="key">Evil Won</div>
          <div class="value">
            {{ stats.n_evilwon }}/{{ stats.n_game }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.n_evilwon_ratio }}%</span>
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="key_value">
          <div class="key">Oberon Won</div>
          <div class="value">
            TODO/{{ stats.n_game }}
            <!-- The unit is optional -->
            <span class="unit">TODO%</span>
          </div>
        </div>
      </div>

    </div>

    <br />

    <div class="row row-equal no-margin">

      <div class="col-sm-6">
        <div class="key_value">
          <div class="key">Evil next to Evil</div>
          <div class="value">
              {{ stats.n_mechmech }}/{{ stats.n_game }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.n_mechmech_ratio }}%</span>
          </div>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="key_value">
          <div class="key">Sylvain & Marc in the same team</div>
          <div class="value">
              {{ stats.n_ssa_and_mpr }}/{{ stats.n_ssa_and_mpr_game }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.n_ssa_and_mpr_ratio }}%</span>
          </div>
        </div>
      </div>

    </div>

    <br />

    <div class="row row-equal no-margin">

      <div class="col-sm-6">
        <div class="key_value">
          <div class="key">Evil won with PED around</div>
          <div class="value">
              {{ stats.withPED_n_evilwon }}/{{ stats.withPED_n_game }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.withPED_n_evilwon_ratio }}%</span>
          </div>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="key_value">
          <div class="key">Evil won without PED around</div>
          <div class="value">
              {{ stats.withoutPED_n_evilwon }}/{{ stats.withoutPED_n_game }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.withoutPED_n_evilwon_ratio }}%</span>
          </div>
        </div>
      </div>

    </div>

    <br />

    <div class="row row-equal no-margin">

      <div class="col-sm-4">
        <div class="key_value">
          <div class="key">TBE is Oberon</div>
          <div class="value">
              {{ stats.tbe_oberon }}/{{ stats.tbe_n_game }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.tbe_oberon_ratio }}%</span>
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="key_value">
          <div class="key">Never Arthur</div>
          <div class="value">
              {{ stats.never_arthur }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.never_arthur_ratio }}% (on {{ stats.never_arthur_n_missions }} missions)</span>
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="key_value">
          <div class="key">Always Arthur</div>
          <div class="value">
              {{ stats.always_arthur }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.always_arthur_ratio }}% (on {{ stats.always_arthur_n_missions }} missions)</span>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

<h4 class="title">Roles (players who were in more than 10 games)</h4>
<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-10">

    <div class="row row-equal no-margin">

      <div class="col-sm-4">
        <div class="key_value">
          <div class="key">Most frequent Merlin</div>
          <div class="value">
            {{ stats.most_frequent_merlin }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.most_frequent_merlin_ratio }}% of games played</span>
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="key_value">
          <div class="key">Most frequent Perceval</div>
          <div class="value">
            {{ stats.most_frequent_perceval }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.most_frequent_perceval_ratio }}% of games played</span>
          </div>
        </div>
      </div>

    </div>

    <br />

    <div class="row row-equal no-margin">

      <div class="col-sm-4">
        <div class="key_value">
          <div class="key">Most frequent Morgana</div>
          <div class="value">
            {{ stats.most_frequent_morgana }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.most_frequent_morgana_ratio }}% of games played</span>
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="key_value">
          <div class="key">Most frequent Mordred</div>
          <div class="value">
            {{ stats.most_frequent_mordred }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.most_frequent_mordred_ratio }}% of games played</span>
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="key_value">
          <div class="key">Most frequent Oberon</div>
          <div class="value">
            {{ stats.most_frequent_oberon }}
            <!-- The unit is optional -->
            <span class="unit">{{ stats.most_frequent_oberon_ratio }}% of games played</span>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

gm/templates/pages/players.html
<h4 class="title">Players with more than {{ min_game }} games</h4>
{% if player_list %}
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
      <table class="table">
        <tr>
          <td>Trigram</td>
          <td># games</td>
          <td># wins</td>
          <td># games (good)</td>
          <td># wins (good)</td>
          <td># games (evil)</td>
          <td># wins (evil)</td>
          <td>% win (good)</td>
          <td>% win (evil)</td>
          <td>% win (total)</td>
        </tr>
        {% for player in player_list %}
          <tr>
            <td style="font-weight: bold">{{ player.tri }} </td>
            <td>{{ player.stats.n_game }} </td>
            <td>{{ player.stats.n_win }} </td>
            <td>{{ player.stats.n_game_good }} </td>
            <td>{{ player.stats.n_win_good }} </td>
            <td>{{ player.stats.n_game_evil }} </td>
            <td>{{ player.stats.n_win_evil }} </td>
            <td>{{ player.stats.pc_win_good|floatformat }}% </td>
            <td>{{ player.stats.pc_win_evil|floatformat }}% </td>
            <td>{{ player.stats.pc_win|floatformat }}% </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% else %}
  <p>No Players yet.</p>
{% endif %}